version: '3'

services:
  db:
    image: postgres:15.1-bullseye
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: swcrmdb
      POSTGRES_USER: sweetcrm
      POSTGRES_PASSWORD: SwCrmTstPwd
